export const cardList = [
  {
    id: 1,
    color: "_orange",
    theme: "Веб-дизайн",
    title: "Задача 1",
    date: "30.10.23",
    status: "Без статуса",
  },
  {
    id: 2,
    color: "_green",
    theme: "Research",
    title: "Задача 2",
    date: "30.10.23",
    status: "Без статуса",
  },
  {
    id: 3,
    color: "_orange",
    theme: "Web Design",
    title: "Задача 3",
    date: "30.10.23",
    status: "Без статуса",
  },
  {
    id: 4,
    color: "_purple",
    theme: "Copywriting",
    title: "Задача 4",
    date: "30.10.23",
    status: "Без статуса",
  },
  {
    id: 5,
    color: "_orange",
    theme: "Веб-дизайн",
    title: "Задача 5",
    date: "30.10.23",
    status: "Без статуса",
  },
  {
    id: 6,
    color: "_green",
    theme: "Research",
    title: "Задача 1",
    date: "30.10.23",
    status: "Нужно сделать",
  },
  {
    id: 7,
    color: "_green",
    theme: "Исследование",
    title: "Задача 1",
    date: "30.10.23",
    status: "В работе",
  },
  {
    id: 8,
    color: "_purple",
    theme: "Копирайтинг",
    title: "Задача 2",
    date: "30.10.23",
    status: "В работе",
  },
  {
    id: 9,
    color: "_orange",
    theme: "Веб-дизайн",
    title: "Задача 3",
    date: "30.10.23",
    status: "В работе",
  },
  {
    id: 10,
    color: "_green",
    theme: "Исследование",
    title: "Задача 1",
    date: "30.10.23",
    status: "Тестирование",
  },
  {
    id: 11,
    color: "_green",
    theme: "Исследование",
    title: "Задача 1",
    date: "30.10.23",
    status: "Готово",
  },
];

export const statusList = [
  "Без статуса",
  "Нужно сделать",
  "В работе",
  "Тестирование",
  "Готово",
];

export default { cardList, statusList };
